# Generated by Django 6.0 on 2025-12-09 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='coordinated_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
