# Generated by Django 6.0 on 2025-12-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='metadata',
            field=models.CharField(),
        ),
    ]
