# Generated by Django 6.0 on 2025-12-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photofavorite_photo_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='original_img',
            field=models.ImageField(upload_to='originals/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_img',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='watermark_img',
            field=models.ImageField(upload_to='watermarks/'),
        ),
    ]
