# Generated by Django 6.0 on 2025-12-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_original_img_alter_photo_thumbnail_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='metadata',
            field=models.CharField(blank=True, null=True),
        ),
    ]
