# Generated by Django 6.0 on 2025-12-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='watermark_img',
            field=models.ImageField(blank=True, null=True, upload_to='watermarks/'),
        ),
    ]
