# Generated by Django 6.0 on 2025-12-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photo_thumbnail_img_alter_photo_watermark_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
