# Generated by Django 6.0 on 2025-12-27 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_coordinators'),
        ('photos', '0007_photo_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
    ]
